name: resume_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

# Current flutter verison 3.13.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  latlng: ^1.0.0
  firebase_core: ^2.10.0
  google_fonts: ^5.0.0
  responsive_builder: ^0.7.0
  get_it: ^7.3.0
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/profile/profile.jpg
  generate: true
